insert into public.cards(id,card_set,color,moves) values
('tiger','base','blue','[[0, 2], [0, -1]]'::jsonb),
('dragon','base','red','[[-2, 1], [2, 1], [-1, -1], [1, -1]]'::jsonb),
('frog','base','red','[[-1, 1], [-2, 0], [1, -1]]'::jsonb),
('rabbit','base','blue','[[1, 1], [2, 0], [-1, -1]]'::jsonb),
('crab','base','blue','[[0, 1], [-2, 0], [2, 0]]'::jsonb),
('elephant','base','red','[[-1, 1], [1, 1], [-1, 0], [1, 0]]'::jsonb),
('goose','base','blue','[[-1, 1], [-1, 0], [1, 0], [1, -1]]'::jsonb),
('rooster','base','red','[[1, 1], [-1, 0], [1, 0], [-1, -1]]'::jsonb),
('monkey','base','blue','[[-1, 1], [1, 1], [-1, -1], [1, -1]]'::jsonb),
('mantis','base','red','[[-1, 1], [1, 1], [0, -1]]'::jsonb),
('horse','base','red','[[0, 1], [-1, 0], [0, -1]]'::jsonb),
('ox','base','blue','[[0, 1], [1, 0], [0, -1]]'::jsonb),
('crane','base','blue','[[0, 1], [-1, -1], [1, -1]]'::jsonb),
('boar','base','red','[[0, 1], [-1, 0], [1, 0]]'::jsonb),
('eel','base','blue','[[-1, 1], [1, 0], [-1, -1]]'::jsonb),
('cobra','base','red','[[1, 1], [-1, 0], [1, -1]]'::jsonb),
('phoenix','sensei','blue','[[-1, 1], [1, 1], [-2, 0], [2, 0]]'::jsonb),
('turtle','sensei','red','[[-2, 0], [2, 0], [-1, -1], [1, -1]]'::jsonb),
('viper','sensei','red','[[0, 1], [-2, 0], [1, -1]]'::jsonb),
('sea_snake','sensei','blue','[[0, 1], [2, 0], [-1, -1]]'::jsonb),
('giraffe','sensei','blue','[[-2, 1], [2, 1], [0, -1]]'::jsonb),
('kirin','sensei','red','[[-1, 2], [1, 2], [0, -2]]'::jsonb),
('iguana','sensei','red','[[-2, 1], [0, 1], [1, -1]]'::jsonb),
('tanuki','sensei','blue','[[0, 1], [2, 1], [-1, -1]]'::jsonb),
('bear','sensei','blue','[[-1, 1], [0, 1], [1, -1]]'::jsonb),
('panda','sensei','red','[[0, 1], [1, 1], [-1, -1]]'::jsonb),
('otter','sensei','red','[[-1, 1], [2, 0], [1, -1]]'::jsonb),
('sable','sensei','blue','[[1, 1], [-2, 0], [-1, -1]]'::jsonb),
('dog','sensei','blue','[[-1, 1], [-1, 0], [-1, -1]]'::jsonb),
('fox','sensei','red','[[1, 1], [1, 0], [1, -1]]'::jsonb),
('rat','sensei','red','[[0, 1], [-1, 0], [1, -1]]'::jsonb),
('mouse','sensei','blue','[[0, 1], [1, 0], [-1, -1]]'::jsonb);
